name-template: 'v$RESOLVED_VERSION-alpha'
tag-template: 'v$RESOLVED_VERSION-alpha'
commitish: main

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'new'
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'patch'
  default: patch

categories:
  - title: '💥 Breaking'
    labels:
      - 'breaking'
  - title: '🚀 New'
    labels:
      - 'feature'
      - 'enhancement'
      - 'new'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: '📝 Docs'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed
  $CHANGES

  > ⚠️ This is an alpha release and may contain breaking changes.

  ## 👥 Contributors
  $CONTRIBUTORS