<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Mocks" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\MongoFlow.csproj" />
  </ItemGroup>

</Project>
