name: Release Drafter

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string
      prerelease-identifier:
        description: 'Version Suffix (alpha, beta, rc, etc)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          version: ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease-identifier != '' }}
          prerelease-identifier: ${{ inputs.prerelease-identifier }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}