name: Release Drafter

on:
  workflow_dispatch:
    inputs:
      prerelease-identifier:
        description: 'alpha, beta, rc, etc'
        required: false
        type: string

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          prerelease-identifier: ${{ inputs.prerelease-identifier }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}